// <auto-generated />
namespace Netblaster.Hermes.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WrongRefFIx : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WrongRefFIx));
        
        string IMigrationMetadata.Id
        {
            get { return "201711151955396_WrongRefFIx"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
